djangojokes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    # User Management
    path('account/', include('users.urls')),
    path('account/', include('allauth.urls')),
    
    # private media
    #path('media/private/', include(private_storage.urls)),
    
    # Local Apps
    path('jobs/', include('jobs.urls')),
    path('jokes/', include('jokes.urls')),
    path('', include('pages.urls')),
   ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
       

jobs/urls.py
from django.urls import path

from .views import JobAppView, JobAppThanksView

app_name = 'jobs'
urlpatterns = [
    path('job-app/', JobAppView.as_view(), name='app'),
    path('job-app/thanks/', JobAppThanksView.as_view(), name='thanks'),
]

templates/pages/about_us.html
{% extends "_base.html" %}

{% block title %}About Us{% endblock %}
{% block main %}
    <h2>About Us</h2>
    <p>We tell funny jokes.</P>
    <p><a href="{% url 'jobs:app' %}">Work for us.</a></p>
{% endblock %}

templates/pages/home.html
{% extends "_base.html" %}

{% load common_tags %}

{% block title %}Home{% endblock %}
{% block main %}
    <h2>Welcome!</h2>
    <p>Ready to Laugh?</P>
{% random_joke %}      
{% endblock %}