djangojokes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    # User Management
    path('account/', include('users.urls')),
    path('account/', include('allauth.urls')),
    
    # private media
    #path('media/private/', include(private_storage.urls)),
    
    # Local Apps
    path('jobs/', include('jobs.urls')),
    path('jokes/', include('jokes.urls')),
    path('', include('pages.urls')),
   ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
       

jobs/urls.py
from django.urls import path

from .views import JobAppView, JobAppThanksView

app_name = 'jobs'
urlpatterns = [
    path('job-app/', JobAppView.as_view(), name='app'),
    path('job-app/thanks/', JobAppThanksView.as_view(), name='thanks'),
]

jokes/urls.py
from django.urls import path

from .views import ( JokeCreateView, JokeDeleteView, JokeDetailView,
                    JokeListView, JokeUpdateView, vote)

app_name = 'jokes'
urlpatterns = [
    path('joke/<slug>/update/', JokeUpdateView.as_view(), name='update'),
    path('joke/<slug>/delete/', JokeDeleteView.as_view(), name='delete'),
    path('joke/create/', JokeCreateView.as_view(), name='create'),
    path('joke/<slug>/', JokeDetailView.as_view(), name='detail'),
    path('joke/<slug>/vote/', vote, name='ajax-vote'),
    path('', JokeListView.as_view(), name='list'),
    path('category/<slug>/', JokeListView.as_view(), name='category'),
    path('tag/<slug>/', JokeListView.as_view(), name='tag'),
    path('creator/<username>/', JokeListView.as_view(), name='creator'),
]

pages/urls.py
from django.urls import path

from .views import AboutUsView, HomePageView

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
  integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
  rel="stylesheet" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<script src="https://kit.fontawesome.com/5705b75f18.js" crossorigin="anonymous"></script>
<link rel="shortcut icon" type="image/png"
  href="{% static 'images/favicon.png' %}">
{% block javascript %}{% endblock %}
<title>{% block title %}{% endblock %} | Django Jokes</title>
</head>
<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'pages:homepage' %}">
      <img src="{% static 'images/logo.png' %}" alt="logo" class="img-fluid"/>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent" aria-expanded="false"
      aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pages:homepage' %}">Home 
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'jokes:list' %}">Jokes</a>
        </li>
        {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
          </li>
      {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
             role="button" data-bs-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            Me
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'my-account' %}">My Account</a>
            <a class="dropdown-item" href="{% url 'jokes:creator' user.username %}
                     ?order={{ order }}&direction={{ direction }}">My Django Jokes</a>
            <div class="dropdown-divider"></div>
            <form method="post" action="{% url 'account_logout' %}">
              {% csrf_token %}
              <button class="btn dropdown-item">Log out</button>
            </form>
          </div>
        </li>
      {% endif %}
      </ul>
      <form class="my-2 my-lg-0" action="{% url 'jokes:list' %}">
        <input class="form-control me-sm-2" type="search"
          placeholder="Search" aria-label="Search" name="q"
          value="{{ request.GET.q }}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
          Search
        </button>
      </form>
    </div>
  </nav>
</header>
<main class="m-4 pb-5">
  {% if messages %}
    <ul>
      {% for message in messages %}
      <div class="alert message{{ message.tags }} alert-dismissible" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    </ul>
  {% endif %}
  {% block main %}<h2>Welcome!</h2>{% endblock %}
</main>
<footer class="fixed-bottom bg-light row">
    <div class="col">
      <div class="float-end m-1 me-2">Copyright &copy; 2022 Django Jokes.</div>
      <nav>
        <ul class="nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'pages:about-us' %}">About</a></li>
          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="/admin/">Admin</a>
            </li>
      {% endif %}
          
        </ul>
    </div>
  </nav>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
  crossorigin="anonymous"
  integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"></script>
</body>
</html>